import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollEffects from "@/components/ScrollEffects";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
        min-h-screen bg-linear-to-r from-black via-zinc-900 to-slate-900
        text-white/90 selection:bg-purple-900/75 selection:text-white`}
      >
        {/* Global scroll effects (reveal, parallax) mounted once for the whole site */}
        <ScrollEffects />
        {children}
      </body>
    </html>
  );
}